Update MortOP_Builder.yml
编译失败提前结束

diff --git a/.github/workflows/MortOP_Builder.yml b/.github/workflows/MortOP_Builder.yml
--- a/.github/workflows/MortOP_Builder.yml
+++ b/.github/workflows/MortOP_Builder.yml
@@ -146,6 +146,11 @@ jobs:
     - name: Check space usage
       if: (!cancelled())
       run: df -hT
+      
+    - name: Check Compile
+      if: steps.compile.outputs.status == 'false'
+      run:  echo "Compile fail" >> $GITHUB_OUTPUT
+            exit 1
 
     - name: Upload bin directory
       uses: actions/upload-artifact@main
